### ISSUE TITLE
Deleting branch fails

### ISSUE THREAD

**Issue by leonard-henriquez** [neondatabase/delete-branch-action#4]
## Steps to reproduce

Use this action while the database branch is running an operation

## Expected result

The branch should be deleted after the operation has finished

## Actual result

The branch is never deleted (which is very problematic because we are limited to 10 branches at the same time, so if we don't delete them, we end up not being able to create new branches).

## Logs, links

https://neon.tech/docs/manage/operations#poll-operation-status

**Comment by leonard-henriquez** [comment]
@raoufchebri is this action still maintained or should I use my fork?
Thanks in advance 🙏

**Comment by duskpoet** [comment]
Good day! This issue should be resolved in the latest version, `v3`. Can you confirm, please?
